### ISSUE TITLE
How to filter for only administrative_data?

### ISSUE THREAD

**Issue by rileyhun** [peter-evans/nominatim-docker#25]
My use case is that I need to forward-geocode unstructured addresses so I can acquire its components: city, state and country. Is there a way to filter the data feeds so that it only includes administrative boundaries given that I don't need a full geodatabase?

**Comment by peter-evans** [comment]
Hi @rileyhun 

I'm afraid I don't know the answer to this. You might be able to get help by asking at the [Nominatim](https://github.com/osm-search/Nominatim) repository, or perhaps with a [`Nominatim` tagged question](https://stackoverflow.com/questions/tagged/nominatim) on Stackoverflow.

**Comment by rileyhun** [comment]
@peter-evans 

Ok - will do, thanks.
