### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by YordanYanakiev** [peter-evans/nominatim-docker#33]
I am sorry that I am probably asking a beginner level questions, but 
- is there a way to see the output of the building session ?
- is there a way to know that the build is completed ?
- is it using all possible processors of the computer and if not - how to change that ?

**Comment by peter-evans** [comment]
> is there a way to see the output of the building session ?
> is there a way to know that the build is completed ?

For these questions please see the readme where it shows how to tail the Docker container logs.
https://github.com/peter-evans/nominatim-docker#usage

> is it using all possible processors of the computer and if not - how to change that ?

I'm not sure about the answer to this. I recommend reading the administration guide which might help with tuning.
https://nominatim.org/release-docs/latest/admin/Import/

**Comment by YordanYanakiev** [comment]
Thank You ! :)
