### ISSUE TITLE
Internal Error : no DB connection

### ISSUE THREAD

**Issue by Namec** [peter-evans/nominatim-docker#7]
hello,

i have just installed nominatim-docker, everything goes well, but when trying to access the web service i have this message on my browser:
============================================================
Internal Server Error
Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.

Message: Failed to establish database connection

SQL Error: DB Error: connect failed

Details:

 [nativecode=pg_connect(): Unable to connect to PostgreSQL server: FATAL:  database "nominatim" does not exist] ** pgsql://@/nominatim 
============================================================

let the force be with you

**Comment by Namec** [comment]
by the way, great work with your repo's : -)

**Comment by peter-evans** [comment]
My guess is that it's failing to build the database from your PBF file. Also remember that it does take hours in some cases to build large databases.

Please could you share what commands you are using to run the docker image.

**Comment by Namec** [comment]
Thank's for your prompte reply,

currently i tried again, using docker commande direclty instead of using my Rancher Orchestrator and it works perfectly. 

actually i had trouble with Nominatim and also OSRM on rancher 2 (K8s), having the message : CrashLoppBackOff.

i'll try again, and let know if i figure out this issue.

**Comment by peter-evans** [comment]
Closing this for now.
